# Generated by Django 3.0.6 on 2020-07-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_item', models.IntegerField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('manufacturer', models.CharField(max_length=100)),
                ('articule', models.CharField(max_length=100)),
                ('dsc', models.CharField(max_length=500)),
                ('one_price', models.IntegerField()),
                ('more_price', models.IntegerField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPORT.Category')),
            ],
        ),
    ]
