# Generated by Django 3.0.6 on 2020-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='dsc',
            field=models.TextField(null=True),
        ),
    ]
