# Generated by Django 3.0.6 on 2020-07-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='more_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='one_price',
            field=models.IntegerField(null=True),
        ),
    ]
