# Generated by Django 3.0.6 on 2020-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0005_auto_20200713_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articule',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
