# Generated by Django 3.0.6 on 2020-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0006_auto_20200713_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='index_item',
            field=models.IntegerField(),
        ),
    ]
