# Generated by Django 3.0.6 on 2020-07-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0007_auto_20200713_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('table_price', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPORT.Item')),
            ],
        ),
    ]
