# Generated by Django 3.0.6 on 2020-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPORT', '0008_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='SPORT.Size'),
        ),
    ]
